
#include "config.h"
#include "timer.h"

void timer_init(void) {

    /* Start 16 MHz crystal oscillator */
    NRF_CLOCK->EVENTS_HFCLKSTARTED = 0;
    NRF_CLOCK->TASKS_HFCLKSTART    = 1;
    while (NRF_CLOCK->EVENTS_HFCLKSTARTED == 0);

	/* start 32kHz crystal oscillator */
	NRF_CLOCK->LFCLKSRC = (CLOCK_LFCLKSRCCOPY_SRC_Xtal << CLOCK_LFCLKSRCCOPY_SRC_Pos);
	NRF_CLOCK->EVENTS_LFCLKSTARTED = 0;
	NRF_CLOCK->TASKS_LFCLKSTART = 1;
	while(!NRF_CLOCK->EVENTS_LFCLKSTARTED);

	/* setup delay routine */
	NRF_RTC0->TASKS_STOP = 1;
	//NRF_RTC0->COUNTER = 0;
	NRF_RTC0->PRESCALER = 0;
	NRF_RTC0->INTENSET = (RTC_INTENSET_COMPARE0_Enabled << RTC_INTENSET_COMPARE0_Pos) |
						 (RTC_INTENSET_COMPARE1_Enabled << RTC_INTENSET_COMPARE1_Pos) |
						 (RTC_INTENSET_COMPARE2_Enabled << RTC_INTENSET_COMPARE2_Pos) |
						 (RTC_INTENSET_COMPARE3_Enabled << RTC_INTENSET_COMPARE3_Pos);

	NRF_RTC0->CC[0] = 0;
	NRF_RTC0->CC[1] = 0;
	NRF_RTC0->CC[2] = 0;
	NRF_RTC0->CC[3] = 0;

	NVIC_SetPriority(RTC0_IRQn, IRQ_PRIORITY_RTC0);
	NVIC_EnableIRQ(RTC0_IRQn);

}

