
#include "config.h"
#include "timer.h"

void timer_init(void) {

	/* start 32kHz crystal oscillator */
	NRF_CLOCK->LFCLKSRC = (CLOCK_LFCLKSRCCOPY_SRC_Xtal << CLOCK_LFCLKSRCCOPY_SRC_Pos);
	NRF_CLOCK->EVENTS_LFCLKSTARTED = 0;
	NRF_CLOCK->TASKS_LFCLKSTART = 1;
	while(!NRF_CLOCK->EVENTS_LFCLKSTARTED);

	/* setup delay routine */
	//NRF_RTC0->COUNTER = 0;
	NRF_RTC0->PRESCALER = 0;
	NRF_RTC0->TASKS_STOP = 1;
	NRF_RTC0->INTENSET = (RTC_INTENSET_COMPARE0_Enabled << RTC_INTENSET_COMPARE0_Pos) |
						 (RTC_INTENSET_COMPARE1_Enabled << RTC_INTENSET_COMPARE1_Pos);

	NVIC_SetPriority(RTC0_IRQn, IRQ_PRIORITY_RTC0);
	NVIC_EnableIRQ(RTC0_IRQn);

	NVIC_SetPriority(RTC1_IRQn, IRQ_PRIORITY_RTC1);
	NVIC_EnableIRQ(RTC1_IRQn);

}

